### PR TITLE
Add new domain

### PR DESCRIPTION
**Pull request by karlhorky**
Hi @Kikobeats ! 👋 Hope you're well.

Seems like this is another free email domain here: https://www.abv.bg/

### CODE REVIEW

**Comment by Kikobeats** [comment]
Hello, can you tell me more about `abv.bg`?

Note the list is auto-generated based on this script
https://github.com/Kikobeats/free-email-domains/blob/master/scripts/postinstall.js

**Comment by karlhorky** [comment]
Oh, I don't know any more. I just had a user sign up with it, and the registration page (translated screenshot below) looks like it is for a free email address:

Screen Shot 2022-06-13 at 12 11 58


If this doesn't match the goals of this project, then I can close the PR.

**Comment by Kikobeats** [comment]
I noted the script was a bit out of date and after update it abv domain is there!
https://github.com/Kikobeats/free-email-domains/commit/c3404521de515a504b3f6de2774954ee1550b44d

**Comment by karlhorky** [comment]
Oh sweet, thanks!

**Pull request closed without merging**
